def count(text, pattern):
    count = 0
    for i in range(0,(len(text)-len(pattern))+1):
        if text[i: i+ len(pattern)] == pattern:
            count += 1
    return count

def freqwords(text, k):
    freqpatterns = []
    count_dict = {}
    for i in range(0, (len(text)- k+ 1)):
        pattern = text[i:i+k]
        count_dict[pattern] = count(text,pattern)
    maxcount = max(count_dict.values())
    print(maxcount)
    for i in range(0,(len(text)- k + 1)):
        for pattern, cnt in count_dict.items():
            if cnt == maxcount:
                freqpatterns.append(pattern)
    unique_list = list(set(freqpatterns))
    print(unique_list)

freqwords("CGGCGGTGCTGTTATGACACCTGAAGTGATGTTATGACACCGGCGGTGCTTCAGGGATGTCAGGGATGCGGCGGTGCTGTTATGACACTCAGGGATGCTTGTTGAGCTTGTTGAGCTGAAGTGATGTTATGACACGTTATGACACCTTGTTGAGCTGAAGTGATGTTATGACACCTTGTTGAGTCAGGGATGGTTATGACACCTTGTTGAGCTGAAGTGATGTTATGACACCTTGTTGAGCGGCGGTGCTCTTGTTGAGCGGCGGTGCTGTTATGACACTCAGGGATGGTTATGACACCGGCGGTGCTCGGCGGTGCTCTTGTTGAGCTGAAGTGATCTGAAGTGATCTTGTTGAGCGGCGGTGCTTCAGGGATGCGGCGGTGCTCTTGTTGAGTCAGGGATGTCAGGGATGCTTGTTGAGCTGAAGTGATGTTATGACACCGGCGGTGCTCGGCGGTGCTCTTGTTGAGCTGAAGTGATCGGCGGTGCTCTTGTTGAGCTGAAGTGATCTGAAGTGATTCAGGGATGGTTATGACACCTGAAGTGATCTTGTTGAGCTGAAGTGATGTTATGACACCTGAAGTGATCTTGTTGAGGTTATGACACCTGAAGTGATCGGCGGTGCTCTTGTTGAGCTTGTTGAGCGGCGGTGCTCGGCGGTGCTTCAGGGATGCTTGTTGAGCTGAAGTGATCTTGTTGAGTCAGGGATGTCAGGGATGCTGAAGTGATCTGAAGTGATTCAGGGATGCTGAAGTGATCGGCGGTGCTCTTGTTGAGGTTATGACACCTGAAGTGATCTTGTTGAGTCAGGGATGCTGAAGTGATGTTATGACACTCAGGGATGTCAGGGATGCGGCGGTGCTCTGAAGTGATCTTGTTGAGCTTGTTGAGCTTGTTGAGCTGAAGTGATCTGAAGTGATCGGCGGTGCT", 13)
